module.exports = [
  {
    name: 'genre',
    joyScale: 2,
    sorrowScale: -2,
    surpriseScale: 0,
    angerScale: 0,
    veryLikelyMood: ['sorrowLikelihood'],
    likelyMood: [],
    possibleMood: ['angerLikelihood'],
    leastUnlikelyMood: [],
  },
  {
    name: 'mode',
    joyScale: 2,
    sorrowScale: -2,
    surpriseScale: 0,
    angerScale: 0,
    veryLikelyMood: ['sorrowLikelihood'],
    likelyMood: [],
    possibleMood: ['angerLikelihood'],
    leastUnlikelyMood: [],
  },
  {
    name: 'valence',
    joyScale: 2,
    sorrowScale: -2,
    surpriseScale: 1,
    angerScale: -1,
    veryLikelyMood: ['sorrowLikelihood'],
    likelyMood: [],
    possibleMood: ['angerLikelihood'],
    leastUnlikelyMood: [],
  },
  {
    name: 'energy',
    joyScale: 2,
    sorrowScale: -1.5,
    surpriseScale: 0,
    angerScale: 1,
    veryLikelyMood: ['sorrowLikelihood'],
    likelyMood: [],
    possibleMood: ['angerLikelihood'],
    leastUnlikelyMood: [],
  },
];
